'use client';
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Nave1 from "./components/Nave Botem/Nave1";
import Botem from "./components/Nave Botem/Botem";
import Product2 from "./components/Product/2Product";
import LeatestProducts from "./components/Product/LeatestProducts";


import Home from "./page";
import Home5 from "./components/Home/Home";
import SelaiderHome from "./components/Home/SelaiderHome/page";
import Selaiderttop from "./components/Selaider Top Categories/page";






// import MyAccount12 from "./components/12";
// import TrendingProducts from "./components/12";











const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Nave1 />
       
        <SelaiderHome/>
        {/* <Home5/> */}

        <Product2 />
        
        
        
        
        
        
        {/* <Selaiderttop/> */}
        
        <Botem />
        {children}
      </body>
    </html>
  );
}
